attributes(global) &
subroutine glm_ss2(U,ch,dt,ix,jx)
!-----------------------------------------------------------------------
!     GLM source term solver
!-----------------------------------------------------------------------
! *** caution ***
! The third argument is changed from dt to (1/2)dt.
! Previously, we use
!   call glm_ss(U,ch,0.5d0*dt,ix,jx)
! but now we use
!   call glm_ss2(U,ch,dt,ix,jx)
!-----------------------------------------------------------------------
  implicit none
  include 'param.h'
!-----------------------------------------------------------------------
! The ratio of the hyperbolic and parabolic effects
!   c_r = ( c_p**2 / c_h ) ~ 0.18
! Ref: Dedner et al. (2002)  p.657, p.661
  real(8), parameter :: cr = 0.2d0
!-----------------------------------------------------------------------
  integer, value :: ix, jx
  real(8), device, intent(inout) :: U(ix,jx,var1)  ! conserved variables (U)
  real(8), device, intent(in) :: ch, dt  ! div cleaning wave speed and the timestep
!-----------------------------------------------------------------------
  integer, device :: i, j
  real(8), device :: f1 = 1.d0

  f1 = exp( -0.5d0*dt*ch/cr )
  j = (blockIdx%y-1)*blockDim%y + threadIdx%y
  i = (blockIdx%x-1)*blockDim%x + threadIdx%x
  U(i,j,ps) = f1 * U(i,j,ps)

  return
end subroutine glm_ss2
